services:
  postgres:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    build:
      context: .
      dockerfile: smtp.Dockerfile
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data: