version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: mindspark-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    build:
      context: .
      dockerfile: redis.Dockerfile
    container_name: mindspark-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

  api:
    build:
      context: ../
      dockerfile: docker/api.Dockerfile
    container_name: mindspark-api
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ../api.mind-spark.ru/app:/app/app
    restart: unless-stopped
    networks:
      - app-network
    
  ml:
    platform: linux/amd64 
    build:
      context: ../
      dockerfile: docker/ml.Dockerfile
    container_name: mindspark-ml
    ports:
      - "8001:8001"
    volumes:
      - ../ml.mind-spark.ru/app:/app/app
    restart: unless-stopped
    networks:
      - app-network
  
  react:
    build:
      context: ../
      dockerfile: docker/react.Dockerfile
    container_name: mindspark-react
    ports:
      - "3000:3000"
    volumes:
      - ../react.mind-spark.ru/src:/app/src
    restart: unless-stopped
    networks:
      - app-network
  
  react-native:
    build:
      context: ../
      dockerfile: docker/react-native.Dockerfile
    container_name: mindspark-react-native
    ports:
      - "8081:8081"
      - "19001:19001" 
      - "19002:19002"
    volumes:
      - ../react-native.mind-spark.ru:/app
    environment:
      - EXPO_DEBUG=true
    stdin_open: true
    tty: true
    command: >
      sh -c "
      IP=$(ip route | awk '/default/ { print $3 }') &&
      export REACT_NATIVE_PACKAGER_HOSTNAME=$IP &&
      export EXPO_PACKAGER_HOSTNAME=$IP &&
      npx expo start --lan --port 8081 --clear
      "
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge