apiVersion: v1
data:
  nginx.conf: |-
    events {
        worker_connections 1024;
    }

    http {
        server {
            listen 80;
            server_name localhost 127.0.0.1 mind-spark.ru www.mind-spark.ru;

            location /api/ {
                proxy_pass http://mindspark-api:8000/;
            }

            location /ml/ {
                proxy_pass http://mindspark-ml:8001/;
            }

            location / {
                proxy_pass http://mindspark-react:3000;
            }
        }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: nginx
  name: nginx-cm0
